name: CI/CD to EC2 via GHCR

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: ghcr.io/lyj0304/cnu-informate-backend:latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build & Push image
        run: |
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: SSH to EC2 and deploy with compose
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}   # PEM 내용
          script_stop: true
          envs: GHCR_USERNAME,GHCR_TOKEN
          script: |
            echo "$GHCR_TOKEN" | docker login ghcr.io -u "$GHCR_USERNAME" --password-stdin
            cd ~/apps/cnu-informate
            # 최신 이미지 가져와서 무중단에 가깝게 교체
            docker compose pull app
            docker compose up -d
            docker image prune -f
